# Generated by Django 2.2.3 on 2020-01-15 05:52

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='product/img'),
        ),
    ]
