# Generated by Django 2.2.3 on 2020-01-15 08:16

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200115_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to=product.models.product_image_path),
        ),
    ]
